apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mlops-pod
  template:
    metadata:
      labels:
        app: mlops-pod
    spec:
      containers:
      - name: mymlopscontainer
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 80
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-secret
              key: GEMINI_API_KEY


---
apiVersion: v1
kind: Service
metadata:
  name: mylb
spec:
  type: LoadBalancer
  selector:
    app: gemini-pod
  ports:
  - port: 80 # Service IP Port
    targetPort: 80 # Container Port